# Generated by Django 5.1.5 on 2025-02-09 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notam_text', models.TextField(max_length=1500)),
                ('part', models.CharField(max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParsedNotams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255, null=True)),
                ('sec_q', models.CharField(max_length=255, null=True)),
                ('sec_a', models.CharField(max_length=255, null=True)),
                ('sec_b', models.CharField(max_length=255, null=True)),
                ('sec_c', models.CharField(max_length=255, null=True)),
                ('sec_d', models.CharField(max_length=255, null=True)),
                ('sec_e', models.TextField(max_length=1500)),
                ('sec_f', models.CharField(max_length=255, null=True)),
                ('created', models.DateTimeField()),
                ('source', models.CharField(max_length=255)),
                ('notam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_notams', to='textprovider.notams')),
            ],
        ),
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('notam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='textprovider.notams')),
            ],
            options={
                'unique_together': {('latitude', 'longitude')},
            },
        ),
    ]
